inherit_gem:
  sanelint:
    - config/default.yml

Style/Documentation:
  Enabled: false

Metrics/BlockLength:
  Exclude:
    - spec/**/*

Rails/Delegate:
  Enabled: false

RSpec/NestedGroups:
  Max: 4