# Ruby CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-ruby/ for more details
#
version: 2
jobs:
  build:
    docker:
      - image: circleci/ruby:2.3

    steps:
      - checkout

      - run:
          name: Setup Code Climate test-reporter
          command: |
            curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
            chmod +x ./cc-test-reporter

      - run:
          name: Install dependencies
          command: bundle install --path vendor/bundle

      - run:
          name: Run tests
          command: |
            ./cc-test-reporter before-build
            bundle exec rspec --format progress --color
            ./cc-test-reporter after-build --coverage-input-type simplecov --exit-code $?

      - run:
          name: Run linter
          command: bundle exec rubocop
