# Ruby CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-ruby/ for more details
#
version: 2
jobs:
  build:
    docker:
      - image: circleci/ruby:2.3-browsers

    steps:
      - checkout

      - type: cache-restore
        name: Restore bundle cache
        key: chain_of_responsibility-bundle-{{ checksum "Gemfile.lock" }}

      - run:
          name: Bundle install
          command: "bundle install --path vendor/bundle"

      - type: save-cache
        name: Store bundle cache
        key: chain_of_responsibility-bundle-{{ checksum "Gemfile.lock" }}
        paths:
          - vendor/bundle

      # Run tests!
      - run: bundle exec rspec --format progress --color

      # Run linter!
      - run: bundle exec rubocop
